#!/bin/sh


LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^(feat|fix|refactor|docs|hotfix)\/[a-z0-9._-]+$"

message="Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. Please rename your branch to a valid name and try again."

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

. "$(dirname "$0")/_/husky.sh"

npm run lint
npx lint-staged